# Generated by Django 5.0.7 on 2024-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModelInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sunlight", models.SmallIntegerField()),
                ("windcurrent", models.SmallIntegerField()),
                ("rainfall", models.SmallIntegerField()),
                ("humidity", models.SmallIntegerField()),
                ("phvalue", models.SmallIntegerField()),
                ("temperature", models.SmallIntegerField()),
                ("topography", models.CharField(max_length=200)),
                ("soiltype", models.CharField(max_length=200)),
                ("soiltexture", models.CharField(max_length=200)),
                ("minerals", models.CharField(max_length=200)),
            ],
        ),
    ]
