# Generated by Django 5.0.7 on 2024-07-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Plantmodel", "0002_mlmodelinput_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mlmodelinput",
            name="soiltexture",
        ),
        migrations.AlterField(
            model_name="mlmodelinput",
            name="humidity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="mlmodelinput",
            name="minerals",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="mlmodelinput",
            name="phvalue",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="mlmodelinput",
            name="rainfall",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="mlmodelinput",
            name="sunlight",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="mlmodelinput",
            name="temperature",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="mlmodelinput",
            name="windcurrent",
            field=models.FloatField(),
        ),
    ]
